project:
  type: website
  output-dir: docs

website:
  title: "Multi-omics Integration Cookbook"
  navbar:
    left:
      - href: index.qmd
        text: Introduction

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

